# Configuración principal de SonarCloud para el Portfolio

# Reemplaza estas dos líneas con las claves que te dé SonarCloud al crear el proyecto
sonar.organization=javieroliver-web
sonar.projectKey=javieroliver-web

# Orígenes del código a analizar
sonar.sources=.

# Archivos a ignorar en el análisis de calidad
sonar.exclusions=assets/**, api/**, README.md, .github/**

# Lenguajes principales del proyecto
sonar.language=js,web,css
